import os
import ConfigParser
import SCons.Environment

output_name='server'
Import('env')
sources= """
	BetDaqRequestThread.cpp
	CMessageProcessor.cpp
	CThreadManager.cpp
	log.cpp
	main.cpp
"""

boos_version_suffix="-1_48"
gcc_version_suffix="-gcc45"

env['Gch'] = env.Gch('stdafx.h')[0]

libs=['zmq', 'boost_filesystem' + boos_version_suffix, 'boost_thread'+boos_version_suffix, 'boost_log'+gcc_version_suffix+ "-mt" + boos_version_suffix]
env.Program(output_name, sources.split(), LIBS=libs, LIBPATH='.')

